apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra

resources:
  - namespace.yaml
  - postgres/configmap.yaml
  - postgres/persistent-volume.yaml
  - postgres/persistent-volume-claim.yaml
  - postgres/deployment.yaml
  - postgres/service.yaml