apiVersion: v1
kind: Service
metadata:
  name: demo-api
  namespace: public-app
  labels:
    app: demo-api
spec:
  type: NodePort
  ports:
    - port: 8080
      name: http
  selector:
    app: demo-api
